# Generated by Django 3.2.6 on 2023-10-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_portfolio_portfolioimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='images',
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.portfolio'),
            preserve_default=False,
        ),
    ]
